/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CleanupsIndexRouteImport } from './routes/cleanups/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as CleanupsNewIndexRouteImport } from './routes/cleanups/new/index'
import { Route as CleanupsCleanupIdIndexRouteImport } from './routes/cleanups/$cleanupId/index'
import { Route as ActionsDietIndexRouteImport } from './routes/actions/diet/index'
import { Route as CleanupsCleanupIdEditRouteImport } from './routes/cleanups/$cleanupId/edit'
import { Route as ActionsDietNewIndexRouteImport } from './routes/actions/diet/new/index'
import { Route as ActionsDietActionIdIndexRouteImport } from './routes/actions/diet/$actionId/index'
import { Route as ActionsDietActionIdEditRouteImport } from './routes/actions/diet/$actionId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupsIndexRoute = CleanupsIndexRouteImport.update({
  id: '/cleanups/',
  path: '/cleanups/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupsNewIndexRoute = CleanupsNewIndexRouteImport.update({
  id: '/cleanups/new/',
  path: '/cleanups/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupsCleanupIdIndexRoute = CleanupsCleanupIdIndexRouteImport.update({
  id: '/cleanups/$cleanupId/',
  path: '/cleanups/$cleanupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsDietIndexRoute = ActionsDietIndexRouteImport.update({
  id: '/actions/diet/',
  path: '/actions/diet/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupsCleanupIdEditRoute = CleanupsCleanupIdEditRouteImport.update({
  id: '/cleanups/$cleanupId/edit',
  path: '/cleanups/$cleanupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsDietNewIndexRoute = ActionsDietNewIndexRouteImport.update({
  id: '/actions/diet/new/',
  path: '/actions/diet/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsDietActionIdIndexRoute =
  ActionsDietActionIdIndexRouteImport.update({
    id: '/actions/diet/$actionId/',
    path: '/actions/diet/$actionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActionsDietActionIdEditRoute = ActionsDietActionIdEditRouteImport.update({
  id: '/actions/diet/$actionId/edit',
  path: '/actions/diet/$actionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/cleanups': typeof CleanupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/signup': typeof SignupIndexRoute
  '/cleanups/$cleanupId/edit': typeof CleanupsCleanupIdEditRoute
  '/actions/diet': typeof ActionsDietIndexRoute
  '/cleanups/$cleanupId': typeof CleanupsCleanupIdIndexRoute
  '/cleanups/new': typeof CleanupsNewIndexRoute
  '/actions/diet/$actionId/edit': typeof ActionsDietActionIdEditRoute
  '/actions/diet/$actionId': typeof ActionsDietActionIdIndexRoute
  '/actions/diet/new': typeof ActionsDietNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/cleanups': typeof CleanupsIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/signup': typeof SignupIndexRoute
  '/cleanups/$cleanupId/edit': typeof CleanupsCleanupIdEditRoute
  '/actions/diet': typeof ActionsDietIndexRoute
  '/cleanups/$cleanupId': typeof CleanupsCleanupIdIndexRoute
  '/cleanups/new': typeof CleanupsNewIndexRoute
  '/actions/diet/$actionId/edit': typeof ActionsDietActionIdEditRoute
  '/actions/diet/$actionId': typeof ActionsDietActionIdIndexRoute
  '/actions/diet/new': typeof ActionsDietNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/cleanups/': typeof CleanupsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/cleanups/$cleanupId/edit': typeof CleanupsCleanupIdEditRoute
  '/actions/diet/': typeof ActionsDietIndexRoute
  '/cleanups/$cleanupId/': typeof CleanupsCleanupIdIndexRoute
  '/cleanups/new/': typeof CleanupsNewIndexRoute
  '/actions/diet/$actionId/edit': typeof ActionsDietActionIdEditRoute
  '/actions/diet/$actionId/': typeof ActionsDietActionIdIndexRoute
  '/actions/diet/new/': typeof ActionsDietNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cleanups'
    | '/login'
    | '/profile'
    | '/signup'
    | '/cleanups/$cleanupId/edit'
    | '/actions/diet'
    | '/cleanups/$cleanupId'
    | '/cleanups/new'
    | '/actions/diet/$actionId/edit'
    | '/actions/diet/$actionId'
    | '/actions/diet/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cleanups'
    | '/login'
    | '/profile'
    | '/signup'
    | '/cleanups/$cleanupId/edit'
    | '/actions/diet'
    | '/cleanups/$cleanupId'
    | '/cleanups/new'
    | '/actions/diet/$actionId/edit'
    | '/actions/diet/$actionId'
    | '/actions/diet/new'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/cleanups/'
    | '/login/'
    | '/profile/'
    | '/signup/'
    | '/cleanups/$cleanupId/edit'
    | '/actions/diet/'
    | '/cleanups/$cleanupId/'
    | '/cleanups/new/'
    | '/actions/diet/$actionId/edit'
    | '/actions/diet/$actionId/'
    | '/actions/diet/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CleanupsIndexRoute: typeof CleanupsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  CleanupsCleanupIdEditRoute: typeof CleanupsCleanupIdEditRoute
  ActionsDietIndexRoute: typeof ActionsDietIndexRoute
  CleanupsCleanupIdIndexRoute: typeof CleanupsCleanupIdIndexRoute
  CleanupsNewIndexRoute: typeof CleanupsNewIndexRoute
  ActionsDietActionIdEditRoute: typeof ActionsDietActionIdEditRoute
  ActionsDietActionIdIndexRoute: typeof ActionsDietActionIdIndexRoute
  ActionsDietNewIndexRoute: typeof ActionsDietNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanups/': {
      id: '/cleanups/'
      path: '/cleanups'
      fullPath: '/cleanups'
      preLoaderRoute: typeof CleanupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanups/new/': {
      id: '/cleanups/new/'
      path: '/cleanups/new'
      fullPath: '/cleanups/new'
      preLoaderRoute: typeof CleanupsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanups/$cleanupId/': {
      id: '/cleanups/$cleanupId/'
      path: '/cleanups/$cleanupId'
      fullPath: '/cleanups/$cleanupId'
      preLoaderRoute: typeof CleanupsCleanupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/diet/': {
      id: '/actions/diet/'
      path: '/actions/diet'
      fullPath: '/actions/diet'
      preLoaderRoute: typeof ActionsDietIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanups/$cleanupId/edit': {
      id: '/cleanups/$cleanupId/edit'
      path: '/cleanups/$cleanupId/edit'
      fullPath: '/cleanups/$cleanupId/edit'
      preLoaderRoute: typeof CleanupsCleanupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/diet/new/': {
      id: '/actions/diet/new/'
      path: '/actions/diet/new'
      fullPath: '/actions/diet/new'
      preLoaderRoute: typeof ActionsDietNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/diet/$actionId/': {
      id: '/actions/diet/$actionId/'
      path: '/actions/diet/$actionId'
      fullPath: '/actions/diet/$actionId'
      preLoaderRoute: typeof ActionsDietActionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/diet/$actionId/edit': {
      id: '/actions/diet/$actionId/edit'
      path: '/actions/diet/$actionId/edit'
      fullPath: '/actions/diet/$actionId/edit'
      preLoaderRoute: typeof ActionsDietActionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  CleanupsIndexRoute: CleanupsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  CleanupsCleanupIdEditRoute: CleanupsCleanupIdEditRoute,
  ActionsDietIndexRoute: ActionsDietIndexRoute,
  CleanupsCleanupIdIndexRoute: CleanupsCleanupIdIndexRoute,
  CleanupsNewIndexRoute: CleanupsNewIndexRoute,
  ActionsDietActionIdEditRoute: ActionsDietActionIdEditRoute,
  ActionsDietActionIdIndexRoute: ActionsDietActionIdIndexRoute,
  ActionsDietNewIndexRoute: ActionsDietNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
